name: update-web
# Hokkaidosm/kcalpunch-webはもろもろの事情によりプライベートとなっています

on:
  push:
    branches:
      - main

jobs:
  update-web:
    runs-on: ubuntu-latest
    steps:
      - name: update-web
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: Hokkaidosm/kcalpunch-web
          event-type: update_data